const users=[{email:'admin@tapngo.com',password:'admin123',role:'Admin',name:'Admin User'},{email:'cashier@tapngo.com',password:'cashier123',role:'Cashier',name:'Cashier User'}];
let products=JSON.parse(localStorage.getItem('tapngo_products')||'null')||[
{id:'P-1001',name:'Milk 1L',sku:'8901001',category:'Dairy',price:250,stock:42,minStock:10},
{id:'P-1002',name:'Bread',sku:'8901002',category:'Bakery',price:180,stock:31,minStock:8},
{id:'P-1003',name:'Rice 5KG',sku:'8901003',category:'Grocery',price:1450,stock:18,minStock:5},
{id:'P-1004',name:'Shampoo',sku:'8901004',category:'Personal Care',price:620,stock:7,minStock:10},
{id:'P-1005',name:'Tea Pack',sku:'8901005',category:'Grocery',price:850,stock:20,minStock:6}
];
let sales=JSON.parse(localStorage.getItem('tapngo_sales')||'null')||[{id:'S-001',date:'2026-05-03',items:[{productId:'P-1001',qty:2,price:250},{productId:'P-1002',qty:1,price:180}],total:680,cashier:'Cashier User'}];
let cart=[];
const app=document.getElementById('app');
function save(){localStorage.setItem('tapngo_products',JSON.stringify(products));localStorage.setItem('tapngo_sales',JSON.stringify(sales));}
function money(n){return 'PKR '+Number(n||0).toLocaleString();}
function route(){const user=localStorage.getItem('tapngo_user');let page=location.hash.replace('#','')||'login';if(!user&&page!=='login')page='login';if(user&&page==='login')page='dashboard';({login,dashboard,productsPage,salesPage,reports}[page]||login)();}
function shell(title,subtitle,content){app.className='phone';app.innerHTML=`<header class="header"><div class="header-row"><div><h1>${title}</h1><p>${subtitle}</p></div><button class="logout" onclick="logout()">⎋</button></div></header><section class="content">${content}</section><nav class="bottom-nav">${nav('dashboard','⌂','Home')}${nav('productsPage','▣','Products')}${nav('salesPage','⌗','Sale')}${nav('reports','▤','Reports')}</nav>`;}
function nav(page,icon,label){const active=(location.hash.replace('#','')||'dashboard')===page?'active':'';return `<a class="tab ${active}" href="#${page}"><span>${icon}</span><span>${label}</span></a>`;}
function logout(){localStorage.removeItem('tapngo_user');location.hash='login';route();}
function login(){app.className='phone login-bg';app.innerHTML=`<div class="brand-box">🛍️</div><h1 class="login-title">Tap N Go</h1><p class="login-text">Mobile POS, inventory, QR/barcode sale and business reports.</p><form class="card space" onsubmit="doLogin(event)"><h2>Sign in</h2><p class="small">Demo: admin@tapngo.com / admin123</p><div id="err"></div><input id="email" class="input" value="admin@tapngo.com" placeholder="Email"><input id="password" class="input" type="password" value="admin123" placeholder="Password"><button class="btn btn-primary btn-full">Login</button></form>`;}
function doLogin(e){e.preventDefault();const email=document.getElementById('email').value.trim();const password=document.getElementById('password').value;const user=users.find(u=>u.email===email&&u.password===password);if(!user){document.getElementById('err').innerHTML='<p class="error">Invalid email or password</p>';return;}localStorage.setItem('tapngo_user',JSON.stringify(user));location.hash='dashboard';route();}
function getDashboard(){const totalSales=sales.reduce((s,x)=>s+x.total,0);const lowStock=products.filter(p=>p.stock<=p.minStock);const categories=[...new Set(products.map(p=>p.category))].map(category=>({category,stock:products.filter(p=>p.category===category).reduce((s,p)=>s+p.stock,0)}));return{totalSales,lowStock:lowStock.length,transactions:sales.length,products:products.length,categories,recentSales:sales.slice(0,5),trend:[3200,4100,3600,5900,4500,totalSales||680]};}
function dashboard(){const d=getDashboard();shell('Dashboard','Retail overview',`<div class="grid-2 mb">${stat('Products',d.products)}${stat('Sales',money(d.totalSales))}${stat('Transactions',d.transactions)}${stat('Low Stock',d.lowStock)}</div><div class="card mb"><h3>Sales Trend</h3><canvas id="lineChart" class="chart"></canvas></div><div class="card"><h3>Recent Sales</h3>${d.recentSales.map(s=>`<div class="row"><span>${s.id}<br><small class="small">${s.date}</small></span><b>${money(s.total)}</b></div>`).join('')}</div>`);drawLine('lineChart',d.trend,['Mon','Tue','Wed','Thu','Fri','Today']);}
function stat(a,b){return `<div class="card"><p class="stat-label">${a}</p><h2 class="stat-value">${b}</h2></div>`;}
function productsPage(){shell('Products','Catalog and inventory',`<form class="card space mb" onsubmit="addProduct(event)"><h3>Add Product</h3><input id="pname" class="input" required placeholder="Product name"><input id="psku" class="input" required placeholder="Barcode / SKU"><div class="grid-2"><input id="pprice" class="input" type="number" value="100" placeholder="Price"><input id="pstock" class="input" type="number" value="10" placeholder="Stock"></div><button class="btn btn-primary btn-full">Save Product</button></form>${products.map(p=>`<div class="card product-card"><div><b>${p.name}</b><p class="small">${p.category} • SKU ${p.sku}</p><span class="badge ${p.stock<=p.minStock?'low':'ok'}">Stock ${p.stock}</span></div><b>${money(p.price)}</b></div>`).join('')}`);}
function addProduct(e){e.preventDefault();products.unshift({id:'P-'+String(1000+products.length+1),name:pname.value,sku:psku.value,category:'Grocery',price:Number(pprice.value),stock:Number(pstock.value),minStock:5});save();productsPage();}
function salesPage(){shell('POS Billing','Scan, bill and update stock',`<div class="card mb"><h3>⌗ QR / Barcode Scanner Demo</h3><div class="flex"><input id="sku" class="input" placeholder="Enter SKU e.g. 8901001"><button onclick="scanSku()" class="btn btn-dark">Add</button></div><p class="small">Camera scanner placeholder: connect a barcode scanner library in a real mobile build.</p></div><div id="saleMsg"></div><div class="card mb"><h3>Quick Products</h3><div class="grid-2">${products.slice(0,6).map(p=>`<button class="quick-btn" onclick="addToCart('${p.id}')"><b>${p.name}</b><br><small>${money(p.price)}</small></button>`).join('')}</div></div><div class="card"><div class="header-row"><h3>Cart</h3><button class="logout" style="color:#111;background:#f1f5f9" onclick="clearCart()">🗑</button></div><div id="cartBox"></div></div>`);renderCart();}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p)return;const e=cart.find(x=>x.productId===p.id);if(e)e.qty++;else cart.push({productId:p.id,name:p.name,qty:1,price:p.price});renderCart();}
function scanSku(){const s=document.getElementById('sku').value.trim();const p=products.find(x=>x.sku===s||x.id===s);if(p){addToCart(p.id);document.getElementById('sku').value='';}}
function renderCart(){const total=cart.reduce((s,i)=>s+i.qty*i.price,0);document.getElementById('cartBox').innerHTML=(cart.length?cart.map(i=>`<div class="row"><span>${i.name} × ${i.qty}</span><b>${money(i.qty*i.price)}</b></div>`).join(''):'<p class="muted center">Cart is empty</p>')+`<div class="row" style="font-size:20px;font-weight:900"><span>Total</span><span>${money(total)}</span></div><button ${!cart.length?'disabled':''} onclick="checkout()" class="btn btn-primary btn-full">Complete Sale</button>`;}
function clearCart(){cart=[];renderCart();}
function checkout(){const clean=cart.map(i=>({...i}));clean.forEach(i=>{const p=products.find(x=>x.id===i.productId);if(p)p.stock=Math.max(0,p.stock-i.qty);});const total=clean.reduce((s,i)=>s+i.qty*i.price,0);const sale={id:`S-${String(sales.length+1).padStart(3,'0')}`,date:new Date().toISOString().slice(0,10),items:clean,total,cashier:'Cashier User'};sales.unshift(sale);cart=[];save();salesPage();document.getElementById('saleMsg').innerHTML=`<div class="success">Sale ${sale.id} completed: ${money(total)}</div>`;}
function reports(){const d=getDashboard();shell('Reports','Sales and inventory analytics',`<button onclick="exportCSV()" class="btn btn-primary btn-full mb">Export CSV Report</button><div class="card mb"><h3>Inventory by Category</h3><canvas id="barChart" class="chart"></canvas></div><div class="card"><h3>Inventory Report</h3><table class="table"><thead><tr><th>Product</th><th>Stock</th><th>Status</th></tr></thead><tbody>${products.map(p=>`<tr><td>${p.name}</td><td>${p.stock}</td><td>${p.stock<=p.minStock?'Low':'OK'}</td></tr>`).join('')}</tbody></table></div>`);drawBar('barChart',d.categories.map(x=>x.stock),d.categories.map(x=>x.category));}
function exportCSV(){const rows=[['Sale ID','Date','Total','Cashier'],...sales.map(s=>[s.id,s.date,s.total,s.cashier])];const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(x=>x.join(',')).join('\n')],{type:'text/csv'}));a.download='tapngo-sales-report.csv';a.click();}
function chartBase(id){const c=document.getElementById(id),ctx=c.getContext('2d');c.width=c.offsetWidth*2;c.height=c.offsetHeight*2;ctx.scale(2,2);return{c,ctx,w:c.offsetWidth,h:c.offsetHeight};}
function drawLine(id,data,labels){const {ctx,w,h}=chartBase(id);const max=Math.max(...data)*1.15;ctx.clearRect(0,0,w,h);ctx.strokeStyle='#e5e7eb';ctx.beginPath();ctx.moveTo(35,15);ctx.lineTo(35,h-35);ctx.lineTo(w-10,h-35);ctx.stroke();ctx.strokeStyle='#16a34a';ctx.lineWidth=3;ctx.beginPath();data.forEach((v,i)=>{const x=35+i*(w-55)/(data.length-1),y=h-35-(v/max)*(h-55);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();ctx.fillStyle='#64748b';ctx.font='10px Arial';labels.forEach((l,i)=>ctx.fillText(l,25+i*(w-55)/(labels.length-1),h-15));}
function drawBar(id,data,labels){const {ctx,w,h}=chartBase(id);const max=Math.max(...data)*1.2;const bw=(w-50)/data.length-10;ctx.clearRect(0,0,w,h);ctx.fillStyle='#16a34a';data.forEach((v,i)=>{const x=35+i*((w-50)/data.length)+5,bh=(v/max)*(h-60);ctx.fillRect(x,h-35-bh,bw,bh);});ctx.fillStyle='#64748b';ctx.font='10px Arial';labels.forEach((l,i)=>ctx.fillText(l.slice(0,6),35+i*((w-50)/labels.length)+2,h-15));}
window.addEventListener('hashchange',route);route();
